# Generated by Django 5.0.6 on 2024-06-24 06:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'العملاء',
                'verbose_name_plural': 'العملاء',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='تودو كب كيك', max_length=30, null=True, verbose_name='أسم المنتج')),
                ('img_prod', models.ImageField(upload_to='product_img', verbose_name='صوره المنتج')),
                ('price', models.FloatField(blank=True, default=220.5, null=True, verbose_name='السعر')),
                ('discount_precent', models.IntegerField(default=50, verbose_name='نسبة الخصم')),
                ('amount', models.IntegerField(default=50, verbose_name='الكمية')),
                ('always_avil', models.BooleanField(verbose_name='هذا المنتج متاح دائما')),
                ('des', models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis itaque cum iure sed sapiente?\n', max_length=300, verbose_name='وصف المنتج')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_3', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'البضائع والمنتجات',
                'verbose_name_plural': 'البضائع والمنتجات',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(blank=True, default='مجهول', max_length=20, null=True, verbose_name='الاسم')),
                ('branch_locat', models.URLField(default='https://www.google.com/maps/place/%D8%A7%D9%84%D9%85%D8%B5%D8%B1%D9%8A%D8%A9+%D9%84%D9%84%D8%B7%D9%8A%D8%B1%D8%A7%D9%86%E2%80%AD/@30.0453066,31.235826,18.5z/data=!4m6!3m5!1s0x145840c643e5389d:0xcc1cea2df59e9d1a!8m2!3d30.0454112!4d31.2357948!16s%2Fg%2F11j2fk3_mn?entry=ttu')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قسم المطاعم',
                'verbose_name_plural': 'قسم المطاعم',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service_provider_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='مجهول', max_length=20, null=True, verbose_name='الاسم')),
                ('address', models.CharField(blank=True, default='45ش المخال-مصر الجديدة', max_length=50, null=True, verbose_name='العنوان')),
                ('branch_locat', models.URLField(blank=True, default='https://www.google.com/maps/place/%D8%A7%D9%84%D9%85%D8%B5%D8%B1%D9%8A%D8%A9+%D9%84%D9%84%D8%B7%D9%8A%D8%B1%D8%A7%D9%86%E2%80%AD/@30.0453066,31.235826,18.5z/data=!4m6!3m5!1s0x145840c643e5389d:0xcc1cea2df59e9d1a!8m2!3d30.0454112!4d31.2357948!16s%2Fg%2F11j2fk3_mn?entry=ttu', null=True, verbose_name='الموقع')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الشركات',
                'verbose_name_plural': 'الشركات',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='web development', max_length=30, null=True, verbose_name='أسم الحدمة')),
                ('img_serve', models.ImageField(upload_to='serve_img', verbose_name='صوره للخدمة')),
                ('price', models.FloatField(blank=True, default=220.5, null=True, verbose_name='السعر')),
                ('des', models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis itaque cum iure sed sapiente?\n', max_length=300, verbose_name='وصف الخدمة')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_4', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='core.service_provider_model')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trader_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='45ش المخال-مصر الجديدة', max_length=50, null=True, verbose_name='العنوان')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قسم التجار',
                'verbose_name_plural': 'قسم التجار',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_profile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, default='مجهول', max_length=20, null=True, verbose_name='الاسم')),
                ('p_type', models.CharField(blank=True, choices=[('تاجر', 'تاجر'), ('عميل', 'عميل'), ('صاحب مطعم', 'صاحب مطعم'), ('موزع خدمات', 'موزع خدمات'), ('أخر', 'أخر')], default=('تاجر', 'تاجر'), max_length=20, null=True, verbose_name='نوع النشاط')),
                ('img_user', models.ImageField(default='media/user_icon.jpg', upload_to='user_img', verbose_name='صوره المستخدم')),
                ('img_bkg', models.ImageField(default='media/bkg_1.jpg', upload_to='user_bkg', verbose_name='خلفبة المستخدم')),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='الهاتف')),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_profile_model',
                'verbose_name_plural': 'User_profile_model',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
