# Generated by Django 5.0.6 on 2024-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_profile_model_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis itaque cum iure sed sapiente?\n', max_length=300, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='trader_model',
            name='branch_locat',
            field=models.URLField(default='https://www.google.com/maps/place/%D8%A7%D9%84%D9%85%D8%B5%D8%B1%D9%8A%D8%A9+%D9%84%D9%84%D8%B7%D9%8A%D8%B1%D8%A7%D9%86%E2%80%AD/@30.0453066,31.235826,18.5z/data=!4m6!3m5!1s0x145840c643e5389d:0xcc1cea2df59e9d1a!8m2!3d30.0454112!4d31.2357948!16s%2Fg%2F11j2fk3_mn?entry=ttu'),
        ),
        migrations.AddField(
            model_name='trader_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis itaque cum iure sed sapiente?\n', max_length=300, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='trader_model',
            name='t_name',
            field=models.CharField(blank=True, default='مجهول', max_length=20, null=True, verbose_name='الاسم'),
        ),
    ]
