# Generated by Django 5.0.6 on 2024-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurant_model_des_trader_model_branch_locat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_model',
            name='address',
            field=models.CharField(blank=True, default='45ش المخال-مصر الجديدة', max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='restaurant_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis itaque cum iure sed sapiente?\n', max_length=300, verbose_name='وصف الفرع'),
        ),
        migrations.AlterField(
            model_name='trader_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis itaque cum iure sed sapiente?\n', max_length=300, verbose_name='وصف النشاط'),
        ),
    ]
