# Generated by Django 5.0.6 on 2024-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurant_model_address_alter_restaurant_model_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis\n', max_length=300, verbose_name='وصف المنتج'),
        ),
        migrations.AlterField(
            model_name='restaurant_model',
            name='branch_locat',
            field=models.URLField(default='https://maps.app.goo.gl/PmEMNyF8A5xRhLzS7'),
        ),
        migrations.AlterField(
            model_name='restaurant_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis\n', max_length=300, verbose_name='وصف الفرع'),
        ),
        migrations.AlterField(
            model_name='service_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis\n', max_length=300, verbose_name='وصف الخدمة'),
        ),
        migrations.AlterField(
            model_name='service_provider_model',
            name='branch_locat',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/PmEMNyF8A5xRhLzS7', null=True, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='trader_model',
            name='branch_locat',
            field=models.URLField(default='https://maps.app.goo.gl/PmEMNyF8A5xRhLzS7'),
        ),
        migrations.AlterField(
            model_name='trader_model',
            name='des',
            field=models.TextField(default='\nSequi repellendus culpa nulla facilis, deserunt ad optio ab neque explicabo perspiciatis libero, impedit facere ut laborum totam. Repudiandae possimus, sit fuga eaque ipsa in minima\n                aut nihil debitis at pariatur odit corporis maxime illo, iste blanditiis\n', max_length=300, verbose_name='وصف النشاط'),
        ),
    ]
