# Generated by Django 5.0.6 on 2024-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_goods_model_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_model',
            name='img_locat',
            field=models.ImageField(default='media/bkg_1.jpg', upload_to='branch_bkg', verbose_name='صوره لمكان الفرع'),
        ),
    ]
