# Generated by Django 5.0.6 on 2024-06-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurant_model_img_locat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='service_provider_model',
            name='img_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_img', verbose_name='شعار الشركة'),
        ),
    ]
