# Generated by Django 5.0.6 on 2024-06-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelname_service_provider_model_img_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_model',
        ),
        migrations.DeleteModel(
            name='ModelName',
        ),
        migrations.AlterField(
            model_name='service_model',
            name='name',
            field=models.CharField(blank=True, default='web development', max_length=30, null=True, verbose_name='أسم الخدمة'),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='p_type',
            field=models.CharField(blank=True, choices=[('تاجر', 'تاجر'), ('عميل', 'عميل'), ('صاحب مطعم', 'صاحب مطعم'), ('موزع خدمات', 'موزع خدمات')], default=('تاجر', 'تاجر'), max_length=20, null=True, verbose_name='نوع النشاط'),
        ),
    ]
